import { useNavigate } from "@tanstack/react-router";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { FileText } from "lucide-react";
import type { ReportSlug } from "@/lib/reports-v2/types";

export interface AutoGenerateProps {
  open: boolean;
  onOpenChange: (o: boolean) => void;
  slug: ReportSlug;
  title: string;
  description: string;
  search?: Record<string, string>;
}

export function AutoGenerateDialog({ open, onOpenChange, slug, title, description, search }: AutoGenerateProps) {
  const navigate = useNavigate();
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <FileText className="h-5 w-5 text-primary" />Gerar relatório?
          </DialogTitle>
          <DialogDescription>{description}</DialogDescription>
        </DialogHeader>
        <div className="rounded-lg border bg-muted/50 p-3 text-sm">
          <div className="font-semibold">{title}</div>
          <div className="mt-1 text-xs text-muted-foreground">Você poderá imprimir ou salvar como PDF na próxima tela.</div>
        </div>
        <DialogFooter className="gap-2 sm:gap-2">
          <Button variant="outline" onClick={() => onOpenChange(false)}>Agora não</Button>
          <Button onClick={() => {
            onOpenChange(false);
            navigate({ to: "/relatorios/$slug", params: { slug }, search: search ?? {} });
          }}>
            Sim, gerar relatório
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
