/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTagsRouteImport } from './routes/_authenticated/tags'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedProducaoRouteImport } from './routes/_authenticated/producao'
import { Route as AuthenticatedIndicadoresRouteImport } from './routes/_authenticated/indicadores'
import { Route as AuthenticatedEstoqueRouteImport } from './routes/_authenticated/estoque'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedCadastrosRouteImport } from './routes/_authenticated/cadastros'
import { Route as AuthenticatedProducaoIndexRouteImport } from './routes/_authenticated/producao.index'
import { Route as AuthenticatedEstoqueIndexRouteImport } from './routes/_authenticated/estoque.index'
import { Route as ApiPublicTagsRouteImport } from './routes/api/public/tags'
import { Route as AuthenticatedRelatoriosQualidadeRouteImport } from './routes/_authenticated/relatorios.qualidade'
import { Route as AuthenticatedRelatoriosProducaoRouteImport } from './routes/_authenticated/relatorios.producao'
import { Route as AuthenticatedRelatoriosEstoqueRouteImport } from './routes/_authenticated/relatorios.estoque'
import { Route as AuthenticatedProducaoNovaRouteImport } from './routes/_authenticated/producao.nova'
import { Route as AuthenticatedProducaoIdRouteImport } from './routes/_authenticated/producao.$id'
import { Route as AuthenticatedEstoqueMovimentacaoRouteImport } from './routes/_authenticated/estoque.movimentacao'
import { Route as AuthenticatedCadastrosTanquesRouteImport } from './routes/_authenticated/cadastros.tanques'
import { Route as AuthenticatedCadastrosProdutosRouteImport } from './routes/_authenticated/cadastros.produtos'
import { Route as AuthenticatedCadastrosParametrosRouteImport } from './routes/_authenticated/cadastros.parametros'
import { Route as AuthenticatedCadastrosEquipamentosRouteImport } from './routes/_authenticated/cadastros.equipamentos'
import { Route as AuthenticatedCadastrosAnalisesRouteImport } from './routes/_authenticated/cadastros.analises'
import { Route as AuthenticatedEstoqueTanquesIdRouteImport } from './routes/_authenticated/estoque.tanques.$id'
import { Route as AuthenticatedCadastrosEquipamentosIdRouteImport } from './routes/_authenticated/cadastros.equipamentos.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTagsRoute = AuthenticatedTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProducaoRoute = AuthenticatedProducaoRouteImport.update({
  id: '/producao',
  path: '/producao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIndicadoresRoute =
  AuthenticatedIndicadoresRouteImport.update({
    id: '/indicadores',
    path: '/indicadores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstoqueRoute = AuthenticatedEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCadastrosRoute = AuthenticatedCadastrosRouteImport.update({
  id: '/cadastros',
  path: '/cadastros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProducaoIndexRoute =
  AuthenticatedProducaoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProducaoRoute,
  } as any)
const AuthenticatedEstoqueIndexRoute =
  AuthenticatedEstoqueIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEstoqueRoute,
  } as any)
const ApiPublicTagsRoute = ApiPublicTagsRouteImport.update({
  id: '/api/public/tags',
  path: '/api/public/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRelatoriosQualidadeRoute =
  AuthenticatedRelatoriosQualidadeRouteImport.update({
    id: '/qualidade',
    path: '/qualidade',
    getParentRoute: () => AuthenticatedRelatoriosRoute,
  } as any)
const AuthenticatedRelatoriosProducaoRoute =
  AuthenticatedRelatoriosProducaoRouteImport.update({
    id: '/producao',
    path: '/producao',
    getParentRoute: () => AuthenticatedRelatoriosRoute,
  } as any)
const AuthenticatedRelatoriosEstoqueRoute =
  AuthenticatedRelatoriosEstoqueRouteImport.update({
    id: '/estoque',
    path: '/estoque',
    getParentRoute: () => AuthenticatedRelatoriosRoute,
  } as any)
const AuthenticatedProducaoNovaRoute =
  AuthenticatedProducaoNovaRouteImport.update({
    id: '/nova',
    path: '/nova',
    getParentRoute: () => AuthenticatedProducaoRoute,
  } as any)
const AuthenticatedProducaoIdRoute = AuthenticatedProducaoIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedProducaoRoute,
} as any)
const AuthenticatedEstoqueMovimentacaoRoute =
  AuthenticatedEstoqueMovimentacaoRouteImport.update({
    id: '/movimentacao',
    path: '/movimentacao',
    getParentRoute: () => AuthenticatedEstoqueRoute,
  } as any)
const AuthenticatedCadastrosTanquesRoute =
  AuthenticatedCadastrosTanquesRouteImport.update({
    id: '/tanques',
    path: '/tanques',
    getParentRoute: () => AuthenticatedCadastrosRoute,
  } as any)
const AuthenticatedCadastrosProdutosRoute =
  AuthenticatedCadastrosProdutosRouteImport.update({
    id: '/produtos',
    path: '/produtos',
    getParentRoute: () => AuthenticatedCadastrosRoute,
  } as any)
const AuthenticatedCadastrosParametrosRoute =
  AuthenticatedCadastrosParametrosRouteImport.update({
    id: '/parametros',
    path: '/parametros',
    getParentRoute: () => AuthenticatedCadastrosRoute,
  } as any)
const AuthenticatedCadastrosEquipamentosRoute =
  AuthenticatedCadastrosEquipamentosRouteImport.update({
    id: '/equipamentos',
    path: '/equipamentos',
    getParentRoute: () => AuthenticatedCadastrosRoute,
  } as any)
const AuthenticatedCadastrosAnalisesRoute =
  AuthenticatedCadastrosAnalisesRouteImport.update({
    id: '/analises',
    path: '/analises',
    getParentRoute: () => AuthenticatedCadastrosRoute,
  } as any)
const AuthenticatedEstoqueTanquesIdRoute =
  AuthenticatedEstoqueTanquesIdRouteImport.update({
    id: '/tanques/$id',
    path: '/tanques/$id',
    getParentRoute: () => AuthenticatedEstoqueRoute,
  } as any)
const AuthenticatedCadastrosEquipamentosIdRoute =
  AuthenticatedCadastrosEquipamentosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedCadastrosEquipamentosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/cadastros': typeof AuthenticatedCadastrosRouteWithChildren
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/estoque': typeof AuthenticatedEstoqueRouteWithChildren
  '/indicadores': typeof AuthenticatedIndicadoresRoute
  '/producao': typeof AuthenticatedProducaoRouteWithChildren
  '/relatorios': typeof AuthenticatedRelatoriosRouteWithChildren
  '/tags': typeof AuthenticatedTagsRoute
  '/cadastros/analises': typeof AuthenticatedCadastrosAnalisesRoute
  '/cadastros/equipamentos': typeof AuthenticatedCadastrosEquipamentosRouteWithChildren
  '/cadastros/parametros': typeof AuthenticatedCadastrosParametrosRoute
  '/cadastros/produtos': typeof AuthenticatedCadastrosProdutosRoute
  '/cadastros/tanques': typeof AuthenticatedCadastrosTanquesRoute
  '/estoque/movimentacao': typeof AuthenticatedEstoqueMovimentacaoRoute
  '/producao/$id': typeof AuthenticatedProducaoIdRoute
  '/producao/nova': typeof AuthenticatedProducaoNovaRoute
  '/relatorios/estoque': typeof AuthenticatedRelatoriosEstoqueRoute
  '/relatorios/producao': typeof AuthenticatedRelatoriosProducaoRoute
  '/relatorios/qualidade': typeof AuthenticatedRelatoriosQualidadeRoute
  '/api/public/tags': typeof ApiPublicTagsRoute
  '/estoque/': typeof AuthenticatedEstoqueIndexRoute
  '/producao/': typeof AuthenticatedProducaoIndexRoute
  '/cadastros/equipamentos/$id': typeof AuthenticatedCadastrosEquipamentosIdRoute
  '/estoque/tanques/$id': typeof AuthenticatedEstoqueTanquesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/cadastros': typeof AuthenticatedCadastrosRouteWithChildren
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/indicadores': typeof AuthenticatedIndicadoresRoute
  '/relatorios': typeof AuthenticatedRelatoriosRouteWithChildren
  '/tags': typeof AuthenticatedTagsRoute
  '/cadastros/analises': typeof AuthenticatedCadastrosAnalisesRoute
  '/cadastros/equipamentos': typeof AuthenticatedCadastrosEquipamentosRouteWithChildren
  '/cadastros/parametros': typeof AuthenticatedCadastrosParametrosRoute
  '/cadastros/produtos': typeof AuthenticatedCadastrosProdutosRoute
  '/cadastros/tanques': typeof AuthenticatedCadastrosTanquesRoute
  '/estoque/movimentacao': typeof AuthenticatedEstoqueMovimentacaoRoute
  '/producao/$id': typeof AuthenticatedProducaoIdRoute
  '/producao/nova': typeof AuthenticatedProducaoNovaRoute
  '/relatorios/estoque': typeof AuthenticatedRelatoriosEstoqueRoute
  '/relatorios/producao': typeof AuthenticatedRelatoriosProducaoRoute
  '/relatorios/qualidade': typeof AuthenticatedRelatoriosQualidadeRoute
  '/api/public/tags': typeof ApiPublicTagsRoute
  '/estoque': typeof AuthenticatedEstoqueIndexRoute
  '/producao': typeof AuthenticatedProducaoIndexRoute
  '/cadastros/equipamentos/$id': typeof AuthenticatedCadastrosEquipamentosIdRoute
  '/estoque/tanques/$id': typeof AuthenticatedEstoqueTanquesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/cadastros': typeof AuthenticatedCadastrosRouteWithChildren
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/estoque': typeof AuthenticatedEstoqueRouteWithChildren
  '/_authenticated/indicadores': typeof AuthenticatedIndicadoresRoute
  '/_authenticated/producao': typeof AuthenticatedProducaoRouteWithChildren
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRouteWithChildren
  '/_authenticated/tags': typeof AuthenticatedTagsRoute
  '/_authenticated/cadastros/analises': typeof AuthenticatedCadastrosAnalisesRoute
  '/_authenticated/cadastros/equipamentos': typeof AuthenticatedCadastrosEquipamentosRouteWithChildren
  '/_authenticated/cadastros/parametros': typeof AuthenticatedCadastrosParametrosRoute
  '/_authenticated/cadastros/produtos': typeof AuthenticatedCadastrosProdutosRoute
  '/_authenticated/cadastros/tanques': typeof AuthenticatedCadastrosTanquesRoute
  '/_authenticated/estoque/movimentacao': typeof AuthenticatedEstoqueMovimentacaoRoute
  '/_authenticated/producao/$id': typeof AuthenticatedProducaoIdRoute
  '/_authenticated/producao/nova': typeof AuthenticatedProducaoNovaRoute
  '/_authenticated/relatorios/estoque': typeof AuthenticatedRelatoriosEstoqueRoute
  '/_authenticated/relatorios/producao': typeof AuthenticatedRelatoriosProducaoRoute
  '/_authenticated/relatorios/qualidade': typeof AuthenticatedRelatoriosQualidadeRoute
  '/api/public/tags': typeof ApiPublicTagsRoute
  '/_authenticated/estoque/': typeof AuthenticatedEstoqueIndexRoute
  '/_authenticated/producao/': typeof AuthenticatedProducaoIndexRoute
  '/_authenticated/cadastros/equipamentos/$id': typeof AuthenticatedCadastrosEquipamentosIdRoute
  '/_authenticated/estoque/tanques/$id': typeof AuthenticatedEstoqueTanquesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/cadastros'
    | '/configuracoes'
    | '/dashboard'
    | '/estoque'
    | '/indicadores'
    | '/producao'
    | '/relatorios'
    | '/tags'
    | '/cadastros/analises'
    | '/cadastros/equipamentos'
    | '/cadastros/parametros'
    | '/cadastros/produtos'
    | '/cadastros/tanques'
    | '/estoque/movimentacao'
    | '/producao/$id'
    | '/producao/nova'
    | '/relatorios/estoque'
    | '/relatorios/producao'
    | '/relatorios/qualidade'
    | '/api/public/tags'
    | '/estoque/'
    | '/producao/'
    | '/cadastros/equipamentos/$id'
    | '/estoque/tanques/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/cadastros'
    | '/configuracoes'
    | '/dashboard'
    | '/indicadores'
    | '/relatorios'
    | '/tags'
    | '/cadastros/analises'
    | '/cadastros/equipamentos'
    | '/cadastros/parametros'
    | '/cadastros/produtos'
    | '/cadastros/tanques'
    | '/estoque/movimentacao'
    | '/producao/$id'
    | '/producao/nova'
    | '/relatorios/estoque'
    | '/relatorios/producao'
    | '/relatorios/qualidade'
    | '/api/public/tags'
    | '/estoque'
    | '/producao'
    | '/cadastros/equipamentos/$id'
    | '/estoque/tanques/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/cadastros'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/estoque'
    | '/_authenticated/indicadores'
    | '/_authenticated/producao'
    | '/_authenticated/relatorios'
    | '/_authenticated/tags'
    | '/_authenticated/cadastros/analises'
    | '/_authenticated/cadastros/equipamentos'
    | '/_authenticated/cadastros/parametros'
    | '/_authenticated/cadastros/produtos'
    | '/_authenticated/cadastros/tanques'
    | '/_authenticated/estoque/movimentacao'
    | '/_authenticated/producao/$id'
    | '/_authenticated/producao/nova'
    | '/_authenticated/relatorios/estoque'
    | '/_authenticated/relatorios/producao'
    | '/_authenticated/relatorios/qualidade'
    | '/api/public/tags'
    | '/_authenticated/estoque/'
    | '/_authenticated/producao/'
    | '/_authenticated/cadastros/equipamentos/$id'
    | '/_authenticated/estoque/tanques/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicTagsRoute: typeof ApiPublicTagsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tags': {
      id: '/_authenticated/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof AuthenticatedTagsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/producao': {
      id: '/_authenticated/producao'
      path: '/producao'
      fullPath: '/producao'
      preLoaderRoute: typeof AuthenticatedProducaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/indicadores': {
      id: '/_authenticated/indicadores'
      path: '/indicadores'
      fullPath: '/indicadores'
      preLoaderRoute: typeof AuthenticatedIndicadoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque': {
      id: '/_authenticated/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AuthenticatedEstoqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cadastros': {
      id: '/_authenticated/cadastros'
      path: '/cadastros'
      fullPath: '/cadastros'
      preLoaderRoute: typeof AuthenticatedCadastrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/producao/': {
      id: '/_authenticated/producao/'
      path: '/'
      fullPath: '/producao/'
      preLoaderRoute: typeof AuthenticatedProducaoIndexRouteImport
      parentRoute: typeof AuthenticatedProducaoRoute
    }
    '/_authenticated/estoque/': {
      id: '/_authenticated/estoque/'
      path: '/'
      fullPath: '/estoque/'
      preLoaderRoute: typeof AuthenticatedEstoqueIndexRouteImport
      parentRoute: typeof AuthenticatedEstoqueRoute
    }
    '/api/public/tags': {
      id: '/api/public/tags'
      path: '/api/public/tags'
      fullPath: '/api/public/tags'
      preLoaderRoute: typeof ApiPublicTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/relatorios/qualidade': {
      id: '/_authenticated/relatorios/qualidade'
      path: '/qualidade'
      fullPath: '/relatorios/qualidade'
      preLoaderRoute: typeof AuthenticatedRelatoriosQualidadeRouteImport
      parentRoute: typeof AuthenticatedRelatoriosRoute
    }
    '/_authenticated/relatorios/producao': {
      id: '/_authenticated/relatorios/producao'
      path: '/producao'
      fullPath: '/relatorios/producao'
      preLoaderRoute: typeof AuthenticatedRelatoriosProducaoRouteImport
      parentRoute: typeof AuthenticatedRelatoriosRoute
    }
    '/_authenticated/relatorios/estoque': {
      id: '/_authenticated/relatorios/estoque'
      path: '/estoque'
      fullPath: '/relatorios/estoque'
      preLoaderRoute: typeof AuthenticatedRelatoriosEstoqueRouteImport
      parentRoute: typeof AuthenticatedRelatoriosRoute
    }
    '/_authenticated/producao/nova': {
      id: '/_authenticated/producao/nova'
      path: '/nova'
      fullPath: '/producao/nova'
      preLoaderRoute: typeof AuthenticatedProducaoNovaRouteImport
      parentRoute: typeof AuthenticatedProducaoRoute
    }
    '/_authenticated/producao/$id': {
      id: '/_authenticated/producao/$id'
      path: '/$id'
      fullPath: '/producao/$id'
      preLoaderRoute: typeof AuthenticatedProducaoIdRouteImport
      parentRoute: typeof AuthenticatedProducaoRoute
    }
    '/_authenticated/estoque/movimentacao': {
      id: '/_authenticated/estoque/movimentacao'
      path: '/movimentacao'
      fullPath: '/estoque/movimentacao'
      preLoaderRoute: typeof AuthenticatedEstoqueMovimentacaoRouteImport
      parentRoute: typeof AuthenticatedEstoqueRoute
    }
    '/_authenticated/cadastros/tanques': {
      id: '/_authenticated/cadastros/tanques'
      path: '/tanques'
      fullPath: '/cadastros/tanques'
      preLoaderRoute: typeof AuthenticatedCadastrosTanquesRouteImport
      parentRoute: typeof AuthenticatedCadastrosRoute
    }
    '/_authenticated/cadastros/produtos': {
      id: '/_authenticated/cadastros/produtos'
      path: '/produtos'
      fullPath: '/cadastros/produtos'
      preLoaderRoute: typeof AuthenticatedCadastrosProdutosRouteImport
      parentRoute: typeof AuthenticatedCadastrosRoute
    }
    '/_authenticated/cadastros/parametros': {
      id: '/_authenticated/cadastros/parametros'
      path: '/parametros'
      fullPath: '/cadastros/parametros'
      preLoaderRoute: typeof AuthenticatedCadastrosParametrosRouteImport
      parentRoute: typeof AuthenticatedCadastrosRoute
    }
    '/_authenticated/cadastros/equipamentos': {
      id: '/_authenticated/cadastros/equipamentos'
      path: '/equipamentos'
      fullPath: '/cadastros/equipamentos'
      preLoaderRoute: typeof AuthenticatedCadastrosEquipamentosRouteImport
      parentRoute: typeof AuthenticatedCadastrosRoute
    }
    '/_authenticated/cadastros/analises': {
      id: '/_authenticated/cadastros/analises'
      path: '/analises'
      fullPath: '/cadastros/analises'
      preLoaderRoute: typeof AuthenticatedCadastrosAnalisesRouteImport
      parentRoute: typeof AuthenticatedCadastrosRoute
    }
    '/_authenticated/estoque/tanques/$id': {
      id: '/_authenticated/estoque/tanques/$id'
      path: '/tanques/$id'
      fullPath: '/estoque/tanques/$id'
      preLoaderRoute: typeof AuthenticatedEstoqueTanquesIdRouteImport
      parentRoute: typeof AuthenticatedEstoqueRoute
    }
    '/_authenticated/cadastros/equipamentos/$id': {
      id: '/_authenticated/cadastros/equipamentos/$id'
      path: '/$id'
      fullPath: '/cadastros/equipamentos/$id'
      preLoaderRoute: typeof AuthenticatedCadastrosEquipamentosIdRouteImport
      parentRoute: typeof AuthenticatedCadastrosEquipamentosRoute
    }
  }
}

interface AuthenticatedCadastrosEquipamentosRouteChildren {
  AuthenticatedCadastrosEquipamentosIdRoute: typeof AuthenticatedCadastrosEquipamentosIdRoute
}

const AuthenticatedCadastrosEquipamentosRouteChildren: AuthenticatedCadastrosEquipamentosRouteChildren =
  {
    AuthenticatedCadastrosEquipamentosIdRoute:
      AuthenticatedCadastrosEquipamentosIdRoute,
  }

const AuthenticatedCadastrosEquipamentosRouteWithChildren =
  AuthenticatedCadastrosEquipamentosRoute._addFileChildren(
    AuthenticatedCadastrosEquipamentosRouteChildren,
  )

interface AuthenticatedCadastrosRouteChildren {
  AuthenticatedCadastrosAnalisesRoute: typeof AuthenticatedCadastrosAnalisesRoute
  AuthenticatedCadastrosEquipamentosRoute: typeof AuthenticatedCadastrosEquipamentosRouteWithChildren
  AuthenticatedCadastrosParametrosRoute: typeof AuthenticatedCadastrosParametrosRoute
  AuthenticatedCadastrosProdutosRoute: typeof AuthenticatedCadastrosProdutosRoute
  AuthenticatedCadastrosTanquesRoute: typeof AuthenticatedCadastrosTanquesRoute
}

const AuthenticatedCadastrosRouteChildren: AuthenticatedCadastrosRouteChildren =
  {
    AuthenticatedCadastrosAnalisesRoute: AuthenticatedCadastrosAnalisesRoute,
    AuthenticatedCadastrosEquipamentosRoute:
      AuthenticatedCadastrosEquipamentosRouteWithChildren,
    AuthenticatedCadastrosParametrosRoute:
      AuthenticatedCadastrosParametrosRoute,
    AuthenticatedCadastrosProdutosRoute: AuthenticatedCadastrosProdutosRoute,
    AuthenticatedCadastrosTanquesRoute: AuthenticatedCadastrosTanquesRoute,
  }

const AuthenticatedCadastrosRouteWithChildren =
  AuthenticatedCadastrosRoute._addFileChildren(
    AuthenticatedCadastrosRouteChildren,
  )

interface AuthenticatedEstoqueRouteChildren {
  AuthenticatedEstoqueMovimentacaoRoute: typeof AuthenticatedEstoqueMovimentacaoRoute
  AuthenticatedEstoqueIndexRoute: typeof AuthenticatedEstoqueIndexRoute
  AuthenticatedEstoqueTanquesIdRoute: typeof AuthenticatedEstoqueTanquesIdRoute
}

const AuthenticatedEstoqueRouteChildren: AuthenticatedEstoqueRouteChildren = {
  AuthenticatedEstoqueMovimentacaoRoute: AuthenticatedEstoqueMovimentacaoRoute,
  AuthenticatedEstoqueIndexRoute: AuthenticatedEstoqueIndexRoute,
  AuthenticatedEstoqueTanquesIdRoute: AuthenticatedEstoqueTanquesIdRoute,
}

const AuthenticatedEstoqueRouteWithChildren =
  AuthenticatedEstoqueRoute._addFileChildren(AuthenticatedEstoqueRouteChildren)

interface AuthenticatedProducaoRouteChildren {
  AuthenticatedProducaoIdRoute: typeof AuthenticatedProducaoIdRoute
  AuthenticatedProducaoNovaRoute: typeof AuthenticatedProducaoNovaRoute
  AuthenticatedProducaoIndexRoute: typeof AuthenticatedProducaoIndexRoute
}

const AuthenticatedProducaoRouteChildren: AuthenticatedProducaoRouteChildren = {
  AuthenticatedProducaoIdRoute: AuthenticatedProducaoIdRoute,
  AuthenticatedProducaoNovaRoute: AuthenticatedProducaoNovaRoute,
  AuthenticatedProducaoIndexRoute: AuthenticatedProducaoIndexRoute,
}

const AuthenticatedProducaoRouteWithChildren =
  AuthenticatedProducaoRoute._addFileChildren(
    AuthenticatedProducaoRouteChildren,
  )

interface AuthenticatedRelatoriosRouteChildren {
  AuthenticatedRelatoriosEstoqueRoute: typeof AuthenticatedRelatoriosEstoqueRoute
  AuthenticatedRelatoriosProducaoRoute: typeof AuthenticatedRelatoriosProducaoRoute
  AuthenticatedRelatoriosQualidadeRoute: typeof AuthenticatedRelatoriosQualidadeRoute
}

const AuthenticatedRelatoriosRouteChildren: AuthenticatedRelatoriosRouteChildren =
  {
    AuthenticatedRelatoriosEstoqueRoute: AuthenticatedRelatoriosEstoqueRoute,
    AuthenticatedRelatoriosProducaoRoute: AuthenticatedRelatoriosProducaoRoute,
    AuthenticatedRelatoriosQualidadeRoute:
      AuthenticatedRelatoriosQualidadeRoute,
  }

const AuthenticatedRelatoriosRouteWithChildren =
  AuthenticatedRelatoriosRoute._addFileChildren(
    AuthenticatedRelatoriosRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCadastrosRoute: typeof AuthenticatedCadastrosRouteWithChildren
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEstoqueRoute: typeof AuthenticatedEstoqueRouteWithChildren
  AuthenticatedIndicadoresRoute: typeof AuthenticatedIndicadoresRoute
  AuthenticatedProducaoRoute: typeof AuthenticatedProducaoRouteWithChildren
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRouteWithChildren
  AuthenticatedTagsRoute: typeof AuthenticatedTagsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCadastrosRoute: AuthenticatedCadastrosRouteWithChildren,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEstoqueRoute: AuthenticatedEstoqueRouteWithChildren,
  AuthenticatedIndicadoresRoute: AuthenticatedIndicadoresRoute,
  AuthenticatedProducaoRoute: AuthenticatedProducaoRouteWithChildren,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRouteWithChildren,
  AuthenticatedTagsRoute: AuthenticatedTagsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicTagsRoute: ApiPublicTagsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
